version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: npm
  directory: "/docker"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
