name: Test
on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 16.x
    - run: node ./src/prebuild.js
    - run: docker-compose build src
    - run: docker-compose up -d
    # - run: docker-compose exec -T test npm install --prefer-offline --no-audit --no-fund --no-update-notifier
    # - run: docker-compose exec -T test npm run test
    - run: docker-compose down --volumes
      if: always()
